### ISSUE TITLE
About cooking techniques and cooking actions

### ISSUE THREAD

**Issue by bimunlp** [majumderb/recipe-personalization#1]
Hi, in your paper you said that you manually construct a list of 58 cooking techniques from 384 cooking actions. Is there any way that I can access these guidelines?
My email address: hanhaishiyi@gmail.com

**Comment by majumderb** [comment]
Thank you for your interest in our paper.

We did not have any specific rules to select those 58 techniques. What we kept in mind that there are certain actions such as 'boil' is common across recipes and do not signify any 'technique', per se. Hence, we removed all such cooking actions which are intermediate steps of cooking any recipes and do not distinguish one recipe from the other.

Hope this helps.

**Comment by bimunlp** [comment]
Thank you for your response and thorough explanation.
Furthermore, I'd like to inquire about your opinion on the  MIT recipe 1M dataset. I noticed that instead of using that dataset, you built your own from food.com. Does the selection reflect any preference?
________________________________
发件人: Bodhisattwa Majumder <notifications@github.com>
发送时间: 2019年9月9日 3:16
收件人: majumderb/recipe-personalization <recipe-personalization@noreply.github.com>
抄送: Hanmeng LIU 刘汉蒙 <liuhanmeng@westlake.edu.cn>; Author <author@noreply.github.com>
主题: Re: [majumderb/recipe-personalization] About cooking techniques and cooking actions (#1)


Thank you for your interest in our paper.

We did not have any specific rules to select those 58 techniques. What we kept in mind that there are certain actions such as 'boil' is common across recipes and do not signify any 'technique', per se. Hence, we removed all such cooking actions which are intermediate steps of cooking any recipes and do not distinguish one recipe from the other.

Hope this helps.

―

**Comment by shuyangli94** [comment]
@yiyouls While the recipe structures are similar between our dataset and the Recipe 1M set, the latter comprises recipe texts and images. In order to personalize our generation, we introduce **700K+ user-recipe reviews** in addition to our structured recipes, to provide a historical action trace. This is one of the benefits of using online community-based recipe aggregators.
