### ISSUE TITLE
How can I preprocess the data?

### ISSUE THREAD

**Issue by gwanghooon** [majumderb/recipe-personalization#2]
There are only raw kaggle data(csv), not preprocessed data(pkl) to train the model.
Is there any addiational code to preprocess the data?

**Comment by shuyangli94** [comment]
The preprocessed data takes the form of the `PP_` files. Some sample code to convert the CSV into PKL (there's no actual preprocessing, just to convert from CSV to PKL formats):
```python
import pandas as pd

df = pd.read_csv('PP_recipes.csv', engine='c')
for col in ['name_tokens', 'ingredient_tokens', 'steps_tokens', 'techniques', 'ingredient_ids']:
    df[col] = df[col].agg(eval)
df.to_pickle('PP_recipes.pkl')
```

**Comment by gwanghooon** [comment]
Thank you.
I can get User and Recipes data,
but how can I get Ingredient map data?

**Comment by shuyangli94** [comment]
It's uploaded as `ingr_map.pkl` on Kaggle.
