### ISSUE TITLE
sample code 

### ISSUE THREAD

**Issue by bitbitsbyte** [majumderb/recipe-personalization#3]
Hi, I have got the recipe_gen code from https://github.com/majumderb/recipe-personalization.git and food-com-recipes-and-user-interactions data. How to train and test the code? Do you have any sample code or README with details? Current README says "the code is tested on a Linux server (with NVIDIA GeForce Titan X Pascal / NVIDIA GeForce GTX 1080 Ti) with PyTorch 1.1.0 and Python 3.6."

**Comment by shuyangli94** [comment]
Thanks for raising this. The `README` has been updated to include the steps:

To train a model, see the [`recipe_gen/models/<model>/train.py`](https://github.com/majumderb/recipe-personalization/blob/master/recipe_gen/models/baseline/train.py) file for that particular model (Baseline `train.py` linked). Likewise, run the `test.py` in the folder with arguments as listed to evaluate.
